## 3. 넘파이
markdown애서 줄바꿈을 할 때는 스페이스 두 번  
markdown애서 제목을 표시할 때는 #기호를 사용함  
#개수에 따라 글자크기가 달라짐  
중요할수록 #개수가 적음

## 3. 넘파이
넘파이란? 다차원배열과 수학 함수를 제공하는 모듈(라이브러리)  
모듈이란? 필요한 기능을 미리 만들어두고 가져다 쓰는 것

3.1 ndarry
다차원 배열
다차원 배열의 특징:
1. 리스트와 비교했을 때 계산 속도가 빠름
2. 리스트와 달리 모든 요소의 타입이 같음

In [6]:
# 먼저 numpy 모듈 가져오기
# 외부에 있는 모듈 파일을 가지고 올 때는 import
# 모듈의 이름이 길 때는 별칭 붇이기
import numpy as np

In [8]:
# 넘파이 배열 만들기
# 입력값:리스트
#결과:넘파이 배열
a = np.array([1,2,3])
a
b= np.array(['a','b','c'])
b

array(['a', 'b', 'c'], dtype='<U1')

## 2차원 배열


In [14]:
# 2차원 배열 생성
# 2차원 배열은 1차원 배열의 묶음
c = np.array([[1,2,3], [4,5,6]])
c
# 3행 3열 크기의 2차원 배열 새성
d = np.array([[1,2,3], [4,5,6], [7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# 주석 단축키 : ctrl + /
# arrange : 숫자 여러개를 생성하는 함수
# 연속된 숫자 10개를 생성
a = np.arange(10)
# 1부터 10까지 생성
b = np.arange(1, 11)
# 1부터 10까지 2씩 건너뛰면서 생성
c = np.arange(1,11,2)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<연습문제>
파이썬 리스트를 넘파이 배열로 변환하여 출력하세요

In [29]:
# scores = [85,90,78,92,88]
arr_scores = np.array([85,90,78,92,88])
print(arr_scores)

# heights = [160,165,170,175,180]
arr_heights = np.array([160,165,170,175,180])
print(arr_heights)

# prices = [1200,1500,1800,2100]
arr_prices = np.array([1200,1500,1800,2100])
print(arr_prices)

# temps = [20,22,19,25,30]
arr_temps = np.array([20,22,19,25,30])
print(arr_temps)

[85 90 78 92 88]
[160 165 170 175 180]
[1200 1500 1800 2100]
[20 22 19 25 30]


In [37]:
# 0부터 4까지 숫자를 원소로 가지는 배열을 생성하세요.
# arange는 파이썬의 range 함수와 비슷
# arange의 반환값:배열
a = np.arange(5)
print(a)

# 0~9
b = np.arange(10)
print(b)

# 3~7
c = np.arange(3,8)
print(c)

# -2~2
d = np.arange(-2, 3)
print(d)

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]
[-2 -1  0  1  2]
