## 제목
### 제목2
마크다운이란? html과 비슷하게 텍스트를 작서하는 언어
#*기호로 제목이나 목록을 작성할 수 있다

In [1]:
# 실행:shift+enter
# 셀 추가 : b
a=5
a

5

In [3]:
var1 = 10
var2 = 20

In [4]:
var1

10

In [5]:
# zeros : 배열을 생성하고 값을 0으로 초기화
# 10개 크기의 배열 생성
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# 3개 크기의 1차원 정수 배열 생성
# 파이썬의 리스트와 달리 넘파이 배열은 모든 원소의 자료형이 같다
a = np.array([1,2,3])
# 배열의 정보를 확인
print(a.dtype) #자료형
print(a.ndim) #배열의 차원
print(a.shape) #행열 크기

int64
1
(3,)


In [7]:
# 2행 3열의 2차원 배열 생성
b = np.array([[1,2,3],[4,5,6]])
print(b.dtype)
print(b.ndim)
print(b.shape)

int64
2
(2, 3)


In [10]:
# 실수형 1차원 배열 생성
arr = np.array([1.1, 2.1,3.1])
# 자료형 확인
arr.dtype
# 배열의 형변환
# float -> int
arr2 = arr.astype(np.int32)
arr2
arr2.dtype

dtype('int32')

In [11]:
# 파이썬의 리스트 생성
lis = [1,2,3]
# 파이썬의 각 원소에 3씩 더하기
# 리스트의 원소에 하나씩 계산하려면 for 반복문을 사용해야한다...
for i in lis:
    print(i+3)

4
5
6


In [12]:
# 넘파이 배열 생성
# 넘파이 배열은 for문 없이 각 원소에 값을 계산할 수 있다!
# 넘파이 배열을 자동으로 각 원소에 반복 수행이 된다
a = np.array([1,2,3])
# 각 원소에 3씩 더하기
a+3

array([4, 5, 6])

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# 배열 두 개를 비교
a > b

array([False, False, False])

인덱스와 슬라이스

In [52]:
# 0~9 숫자 만들고 1차원 배열 생성
a = np.arange(10)
print(a)
# 배열의 원소 하나 꺼내기
a[1]
# 범위로 값 꺼내기 (슬라이스)
a[3:6]
# 원소 값 변경하기
# 두번째 원소의 값 변경하기
a[1] = 99
a
# 특정 범위에 있는 값을 모두 변경하기
# 3,4,5 번째 데이터 변경
a[3:6] = 88
a

[0 1 2 3 4 5 6 7 8 9]


array([ 0, 99,  2, 88, 88, 88,  6,  7,  8,  9])

In [23]:
# 배열 전체 선택
# a를 출력하는 것과 같다
a[:]

array([ 0, 99,  2, 88, 88, 88,  6,  7,  8,  9])

In [24]:
# 슬라이스로 배열 전체를 선택하고, 값 변경
a[:] = 999
a

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

<연습문제>

In [41]:
# 배열의 첫 번째 값을 꺼내서 출력
arr = np.array([10,20,30,40,50])
print(arr[0])

# 배열의 세 번째 값을 꺼내서 출력
print(arr[2])

# 배열의 마지막 값을 꺼내서 출력
print(arr[4])

# 배열의 두 번째 값을 200으로 바꾸세요
arr[1] = 200
arr

# 배열의 네 번째 값을 999로 바꾸세요
arr[3] = 999
arr

10
30
50


array([ 10, 200,  30, 999,  50])

In [48]:
arr = np.array(["가","나", "다","라","마"])

# 배열의 두 번째 값을 꺼내서 출력
print(arr[1])

# 배열의 네 번째 값을 꺼내서 출력 
print(arr[3])

# 배열의 마지막 값을 꺼내서 출력
print(arr[-1])

# 배열의 첫 번째 값을 '하'로 바꾸세요
arr[0] = '하'
arr

# 배열의 세 번째 값을 '호'로 바꾸세요
arr[2] = '호'
arr

나
라
마


array(['하', '나', '호', '라', '마'], dtype='<U1')

In [57]:
arr = np.array([10,20,30,40,50,60,70])

# 배열의 처음 3개 값을 꺼내서 출력
arr[0:3]

# 배열의 네번째~끝 값을 꺼내서 출력
arr[3:]

# 배열의 두번째~다섯번째 값을 꺼내서 출력
arr[1:5]

array([20, 30, 40, 50])

In [61]:
arr = np.array(["a","b", "c","d","e","f","g"])

# 배열의 처음 3개 값을 꺼내서 출력
arr[0:3]

# 배열의 네번째~끝 값을 꺼내서 출력
arr[3:]

# 배열의 두번째~다섯번째 값을 꺼내서 출력
arr[1:5]


array(['b', 'c', 'd', 'e'], dtype='<U1')

2차원 배열의 인덱싱

In [62]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
# 2차원 배열의 인덱스
# 행(인덱스)
# 열(컬럼)
# 첫번째 행 꺼내기
arr[0]

array([1, 2, 3])

In [69]:
# 1 꺼내기
arr[0][0]
# 9 꺼내기
arr[2][2]
# 5 꺼내기
arr[1][1]
arr[1,1]

np.int64(5)

In [72]:
# 배열 원소의 값 바꾸기
# 0 -> 1
arr[0][0] = 0
arr

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2차원 배열 슬라이스

In [73]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
# 헹을 기준으로 슬라이스
# 처음부터 두 번째 행까지
arr[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
# 행:1번 2번
# 열:1번 2번
arr[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [78]:
# 행:0번 1번
# 열:0번 1번
arr[ :2, :2 ]

array([[1, 2],
       [4, 5]])

In [ ]:
# 행: 1번 행만 선택
# 열:0 1번
arr[1,0:2]

<연습문제>

In [104]:
arr = np.array([[10,20,30], 
                [40,50,60],
                [70,80,90]])

# 첫 번째 행의 두 번째 값을 꺼내서 출력
arr[0,1]

# 세 번째 행의 첫 번째 값을 꺼내서 출력
arr[2,0]

# 두 번째 행 전체를 꺼내서 출력
arr[:,1]

# 두 번째 열 전체를 꺼내서 출력
arr[0,0:2]

# 첫 번째 행의 세 번째 값을 300으로 바꾸시오
arr[0,2] = 300
arr

array([[ 10,  20, 300],
       [ 40,  50,  60],
       [ 70,  80,  90]])

In [113]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

# 두 번째 행의 세 번째 값을 꺼내서 출력
arr[1,2]

# 네 번째 행의 첫 번째 값을 꺼내서 출력
arr[3,0]

# 세 번째 행 전체를 꺼내서 출력
arr[2,:]

# 네 번째 열 전체를 꺼내서 출력
arr[:,3]

# 첫 번째 행의 네 번째 값을 100으로 바꾸시오
arr[0,3] = 100
arr

array([[  1,   2,   3, 100],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [124]:
arr = np.array([[10,20,30], 
                [40,50,60],
                [70,80,90]])

# 첫 번째 행의 앞 2개 숫자를 꺼내서 출력하세요
arr[0,0:2]

# 두 번째 행부터 세 번째 행까지 전체를 꺼내서 출력
arr[1:3,:]

# 모든 행에서 두 번째와 세 번째 열만 꺼내서 출력
arr[:,1:3]

array([[20, 30],
       [50, 60],
       [80, 90]])

불리인 인덱스  
인덱스란? 데이터의 위치

In [130]:
import numpy as np

# 학생 배열 생성
students = np.array(['철수','영희','인수','철수','철수'])

# 도서 정보 (2차원 배열)
books = np.array([
    ['수학의 정석', 7], 
    ['해리포터', 10], 
    ['피아니스트', 5], 
    ['한국사', 5], 
    ['데미안', 12]
])

In [131]:
# 여기서 철수의 대출 이력만 조회하기
# 배열 == '비교값'
# 배열 전체에 철수를 비교
# 총 5번 비교하고 bool 배열 반환
arr = (students == '철수')
arr

array([ True, False, False,  True,  True])

In [133]:
# books 배열의 인덱스에 bppl 배열 넣기
books[students == '철수']

array([['수학의 정석', '7'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

In [135]:
print(students != '철수')
# 철수가 아닌 대출 이력 찾기
# true에 해당하는 원소만 반환
books[students != '철수']

[False  True  True False False]


array([['해리포터', '10'],
       ['피아니스트', '5']], dtype='<U21')

In [138]:
# '수학의 정석'을 찾아서 제목을 '자바의 정석'으로 바꾸기
books == '수학의 정석'
# bool 배열로 원소를 찾고 값 교체
books[books == '수학의 정석'] = '자바의 정석'
books

array([['자바의 정석', '7'],
       ['해리포터', '10'],
       ['피아니스트', '5'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

In [142]:
# 대출 이력 중에서 철수가 아닌 항목을 찾고 
# 행 전체를 7로 바꾸기
students != '철수'
books[students != '철수'] = 7
books

array([['자바의 정석', '7'],
       ['7', '7'],
       ['7', '7'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

<연습문제>

In [152]:
arr = np.array([10,20,30,40,50,60,70])

# 배열에서 30보다 큰 값만꺼내서 출력하세요
# 조건 만족 -> 불리언 인덱스
print(arr>30)
print(arr[arr>30])

# 배열에서 짝수 값만 꺼내소 출럭
arr[arr%2 == 0]

# 배열에서 50보단 큰 값을 모두 999로 바꿔
arr[arr>50] = 999
arr

[False False False  True  True  True  True]
[40 50 60 70]


array([ 10,  20,  30,  40,  50, 999, 999])

In [159]:
# 직원 이름 배열
employees = np.array(['짱구','철수','유리','맹구','훈이'])

# 직원별 월급 (만원 단위)
salaries = np.array([250,320,280,400,150])

# 직원 이름과 월급은 대응

# '맹구'의 급여를 조회하세요.
salaries[employees == '맹구']
# 급여가 300만원 이상인 직원들의 이름을 출력하세요.
employees[salaries>=300]
# 급여가 200만원 미만인 직원들의 급여를 모두 200으로 올리세요
salaries[salaries<200] = 200
salaries


array([250, 320, 280, 400, 200])

3.2 배열의 모양 바꾸기

In [161]:
# 1~9 숫자가 담긴 1차원 배열에 생성
# reshape : 배열의 형태를 바꾸는 함수
# 1차원 -> 2차원
# 3행 3열 크기의 배열로 변환
print(np.arange(1,10))
arr = np.arange(1,10).reshape(3,3)
arr
# 

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [162]:
# 1~16 숫자가 담긴 1차원 배열
# 1차원 -> 2차원
print(np.arange(1,17))
a = np.arange(1,17).reshape(4,4)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [164]:
#1~12 1차원 배열
# 이 배열을 3행 4열 배열로 변환
print(np.arange(1,13))
a = np.arange(1,13).reshape(3,4)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [172]:
# 0부터 11까지 숫자를 생성한 뒤, 3행 4열 배열로 바꾸세요.
print(np.arange(0,12))
a = np.arange(0,12).reshape(3,4)
print(a)

# 1부터 16까지 숫자를 생성한 뒤, 4행 4열 배열로 바꾸세요.
print(np.arange(1,17))
a = np.arange(1,17).reshape(4,4)
print(a)

# 1부터 20까지 숫자를 생성한 뒤, 5행 4열 배열로 바꾸세요.
print(np.arange(1,21))
a = np.arange(1,21).reshape(5,4)
print(a)

# 10부터 25까지 숫자를 생성한 뒤, 4행 4열 배열로 바꾸세요.
print(np.arange(10,26))
a = np.arange(10,26).reshape(4,4)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


3.3 난수를 생성하는 방법  
난수란? 랜덤값

In [173]:
# 랜덤값 만들기
# 표준 정규 분포 : 표준 편차가 1인 그래프에서 랜덤값을 생성 (-3 ~ 3)
# 랜덤값 10개 생성
arr = np.random.standard_normal(size=10)
arr

array([ 1.69356583, -2.32123112,  1.06647798,  2.41810552, -2.27741965,
        0.31759952,  1.1873054 , -0.22423065, -1.43868583,  0.9777659 ])

In [174]:
# 균일 분포 : 범위 0~1. 모든 값이 같은 확률로 나옴
arr = np.random.uniform(size=10)
arr


array([0.57302728, 0.72336248, 0.27380065, 0.11510051, 0.83463713,
       0.38145765, 0.96784099, 0.02428253, 0.79733675, 0.92291653])

<연습문제>

In [177]:
# 표준 정규 분포에서 랜덤값 5개 생성
arr = np.random.standard_normal(size=5)
print(arr)

# 균일 분포에서 랜덤값 5개 생성
arr = np.random.uniform(size=5)
print(arr)

[ 0.15591011 -0.28250867  0.90517499 -0.49070698  0.79320379]
[0.72076397 0.64892375 0.93619639 0.7997729  0.32842586]


3.4 유니버셜 함수  
반복문없이 배열 전체에 계산을 해주는 함수

In [178]:
# 0~9 숫자가 담긴 1차원 배열 생성
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
# 파이썬의 리스트는 for문을 사용해서 계산해야함
# 넘파이의 배열은 for문 없이 계산 가능
# 배열 전체에 3 더하기
# add : 더하기
np.add(arr,3)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [182]:
a = np.array([1,7,2,4,10])
b = np.array([3,4,5,6,7])

# 두 배열을 비교하여 더 큰 값 저장하기
np.maximum(a,b)

array([ 3,  7,  5,  6, 10])

조건문

In [187]:
# # 배열 두 개 만들기
# a = np.array([1,2,3])
# b = np.array([10,20,30])
# # 불리언 배열 만들기(조건)
# cond = np.array([True, True, False])

a = np.array([1,2,3])
b = np.array([10,20,30])
cond = np.array([True, True, False])

In [188]:
# where(조건, 참일때값, 거짓일때값) : 조건문 쓰기
# 조건이 참이면 a에서 값을 선댁, 거짓이면 b에서 값을 선택        
result = np.where(cond, a, b)
print(result)

[ 1  2 30]


In [186]:
# 1차원 배열 생성
arr = np.array([-2,-1,0,1,2])

# 양수면 'o', 음수면 'x'로 반환
# 조건, 참일때값, 거짓일때값
# 조건이 true면 o를 선택, false면 x를 선택
print(arr>0)
np.where(arr > 0, 'o','x')

# 조건배열 만들기


[False False False  True  True]


array(['x', 'x', 'x', 'o', 'o'], dtype='<U1')

<연습문제>

In [196]:
# 배열 [5,12,7,20,3]에서
# 10보다 크면 '100', 10 이하면 '0'으로 바꾸세요.

arr>10
np.where(arr>10,'100','0')

# 배열 [15,8,22,6,13]에서
# 짝수면 1, 홀수면 -1로 바꾸세요.
arr = np.array([15,8,22,6,13])
arr[arr%2 == 1] = -1
print(arr)
arr[arr%2 == 0] = 1
print(arr)

# 배열 [10,20,30,40,50]과 [1,2,3,4,5]을 만들고 조건배열 [True, False, True, False, True] 를 사용해 
# 조건이 True일 때는 첫 번째 배열 값, False일 때는 두 번째 배열값을 선택 
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([1,2,3,4,5])
cond = np.array([True, False, True, False, True])
np.where(cond,arr1,arr2)

[-1  8 22  6 -1]
[-1  1  1  1 -1]


array([10,  2, 30,  4, 50])

통계를 구할 때 자주 사용하는 함수들  
(최대한 최소 합계 평균)

In [201]:
# 파이썬의 리스트 생성
lis = [1,2,3,4,5]
# 리스트의 총합을 구하세요
sum=0
for i in lis:
    sum=sum+i
# 리스트의 평균을 구하세요
print(sum/len(lis))

3.0


In [203]:
# 넘파이 배열로 합계와 평균 구하기
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.mean(arr))
# 배열에서 제일 큰 값
print(np.max(arr))
# 배열에서 제일 작은 값
print(np.min(arr))

15
3.0
5
1


<연습문제>

In [207]:
# 칼로리
arr = np.array([250,550,400,800])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

# 운동한 시간
arr = np.array([30,45,60,20,40,50,35])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

2000
500.0
800
250
280
40.0
60
20


행/열 단위로 합계 구하기

In [215]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

# 배열의 합계 구하기
arr.sum()
# 2차원 배열에서 행 또는 열 방향으로 합 구하기
# axis:0 -> 세로 방향으로 합 계산
arr.sum(axis=0)
# axis=1 -> 가로 방향으로 합 계산
arr.sum(axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [216]:
# 누적값 구하기
# 합을 구하는 중간 과정을 보여줌
arr = np.array([1,2,3,4,5])
arr.cumsum()

array([ 1,  3,  6, 10, 15])

In [220]:
# 2차원 배열 생성
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr)
# 2차원 배열의 누적값 구하기
# 기준 설정(세로방향, 위->아래)
# 앞에 있는 수를 더한 결과
print(arr.cumsum(axis=0))
# 
print(arr.cumsum(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
